package main

import (
	_ "embed"
	"strings"
)

// synonymExpansionWeight is the TF weight given to synonym-expanded tokens.
// Original query tokens keep their full weight; synonyms get this fraction.
const synonymExpansionWeight = 0.3

// wordnetSynonyms is the pre-processed WordNet 3.1 synonym data.
// Generated by: go run ./cmd/gensynonyms /path/to/wordnet/dict > wordnet_synonyms.txt
// Format: one synonym group per line, tab-separated Porter-stemmed words.
//
//go:embed wordnet_synonyms.txt
var wordnetSynonyms string

// synonymIndex maps each stemmed term to all its synonyms (from all synsets
// containing that term). Built once at init(), never mutated — safe for
// concurrent reads. A word appearing in multiple WordNet synsets will have
// the union of all synonym peers across those synsets.
var synonymIndex map[string][]string

func init() {
	lines := strings.Split(wordnetSynonyms, "\n")

	// First pass: collect all synonyms per term across all groups.
	termSyns := make(map[string]map[string]struct{}, len(lines)*2)
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		group := strings.Split(line, "\t")
		if len(group) < 2 {
			continue
		}
		for _, term := range group {
			if _, ok := termSyns[term]; !ok {
				termSyns[term] = make(map[string]struct{})
			}
			for _, other := range group {
				if other != term {
					termSyns[term][other] = struct{}{}
				}
			}
		}
	}

	// Second pass: convert sets to slices.
	synonymIndex = make(map[string][]string, len(termSyns))
	for term, syns := range termSyns {
		others := make([]string, 0, len(syns))
		for syn := range syns {
			others = append(others, syn)
		}
		synonymIndex[term] = others
	}
}

// expandQueryVectorCorpus injects synonym tokens into a query vector, but only
// for synonyms that actually appear in the corpus (tokenIndex). This avoids
// polluting the query with broad WordNet synonyms that can't match anything.
func expandQueryVectorCorpus(qVec map[string]float64, corpusTokens map[string]map[string]struct{}) map[string]float64 {
	expanded := make(map[string]float64, len(qVec))
	for tok, weight := range qVec {
		expanded[tok] = weight
	}
	for tok, weight := range qVec {
		if syns, ok := synonymIndex[tok]; ok {
			for _, syn := range syns {
				if _, inCorpus := corpusTokens[syn]; !inCorpus {
					continue
				}
				w := weight * synonymExpansionWeight
				if expanded[syn] < w {
					expanded[syn] = w
				}
			}
		}
	}
	return expanded
}

// expandTokenSetCorpus expands a token set with synonym group members that
// actually appear in the corpus.
func expandTokenSetCorpus(tokens map[string]struct{}, corpusTokens map[string]map[string]struct{}) map[string]struct{} {
	expanded := make(map[string]struct{}, len(tokens))
	for tok := range tokens {
		expanded[tok] = struct{}{}
	}
	for tok := range tokens {
		if syns, ok := synonymIndex[tok]; ok {
			for _, syn := range syns {
				if _, inCorpus := corpusTokens[syn]; !inCorpus {
					continue
				}
				expanded[syn] = struct{}{}
			}
		}
	}
	return expanded
}
